development:
  adapter: postgresql
  database: potencia_em_grupo_development
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  database: potencia_em_grupo_test
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: potencia_em_grupo_production
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000
  template: template0