development:
  adapter: postgresql
  database: rails32template_development
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: rails32template_test
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rails32template_production
  host: localhost
  user: postgres
  password:
  pool: 5
  timeout: 5000

